# Generated by Django 4.1.2 on 2023-03-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth')], max_length=15)),
                ('Sem_Subject', models.CharField(choices=[('1', (('IIT', 'IIT'), ('C-Prog.', 'C-Prog.'), ('DL', 'DL'), ('Math', 'Math'), ('Physics', 'Physics'))), ('2', (('DS', 'DS'), ('OOP', 'OOP'), ('MP', 'MP'), ('MATH-II', 'MATH-II'), ('STAT-I', 'STAT-I'))), ('3', (('DSA', 'DSA'), ('NM', 'NM'), ('CA', 'CA'), ('CG', 'CG'), ('STAT-II', 'STAT-II'))), ('4', (('TOC', 'TOC'), ('CN', 'CN'), ('OS', 'OS'), ('DBMS', 'DBMS'), ('AI', 'AI'))), ('5', (('DAA', 'DAA'), ('SAD', 'SAD'), ('CRYPTO', 'CRYPTO'), ('SAM', 'SAM'), ('WT', 'WT'), ('SAE', 'SAE'))), ('6', (('SE', 'SE'), ('CDC', 'CDC'), ('E-GOV', 'E-GOV'), ('NCC', 'NCC'), ('TW', 'TW'), ('E-COM', 'E-COM'))), ('7', (('AJP', 'AJP'), ('DW & DM', 'DW & DM'), ('POM', 'POM'), ('P-WORK', 'P-WORK'), ('IR', 'IR'), ('DA', 'DA'), ('SPM', 'SPM'), ('NS', 'NS'), ('DSD', 'DSD'))), ('8', (('AD', 'AD'), ('CC', 'CC'), ('AN-IPV6', 'AN-IPV6'), ('DSS & ES', 'DSS & ES'), ('DN', 'DN'), ('ESP', 'ESP'), ('GT', 'GT'), ('GS', 'GS'), ('IM', 'IM'), ('MAD', 'MAD'), ('NSA', 'NSA'), ('RTS', 'RTS')))], max_length=15)),
                ('MicroSyllabus_file', models.FileField(blank=True, default='NULL', null=True, upload_to='')),
                ('Book_file', models.FileField(blank=True, default='NULL', null=True, upload_to='')),
                ('Question_file', models.FileField(blank=True, default='NULL', upload_to='')),
                ('Sub_discription', models.CharField(max_length=100)),
                ('Sub_image', models.ImageField(upload_to='subject_img')),
            ],
        ),
    ]
