# Generated by Django 4.1.2 on 2023-03-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_alter_item_sub_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Note_file',
            field=models.FileField(blank=True, default='NULL', null=True, upload_to=''),
        ),
    ]
