# Generated by Django 4.1.2 on 2023-03-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_item_note_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Sem_Subject',
            new_name='Subject',
        ),
        migrations.AlterField(
            model_name='item',
            name='Semester',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eighth')], max_length=15),
        ),
    ]
