# Generated by Django 4.1.2 on 2023-03-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_rename_sem_subject_item_subject_alter_item_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Sub_discription',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='Sub_image',
            field=models.ImageField(null=True, upload_to='subject_img'),
        ),
    ]
