# Generated by Django 4.1.2 on 2023-03-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_alter_item_sub_discription_alter_item_sub_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='subject_img'),
        ),
    ]
