# Generated by Django 4.1.2 on 2023-04-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_alter_item_sub_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=20)),
                ('Note_file', models.FileField(blank=True, default='NULL', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('Question_file', models.FileField(blank=True, default='NULL', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eighth')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(choices=[('1', (('IIT', 'IIT'), ('C-Prog.', 'C-Prog.'), ('DL', 'DL'), ('Math', 'Math'), ('Physics', 'Physics'))), ('2', (('DS', 'DS'), ('OOP', 'OOP'), ('MP', 'MP'), ('MATH-II', 'MATH-II'), ('STAT-I', 'STAT-I'))), ('3', (('DSA', 'DSA'), ('NM', 'NM'), ('CA', 'CA'), ('CG', 'CG'), ('STAT-II', 'STAT-II'))), ('4', (('TOC', 'TOC'), ('CN', 'CN'), ('OS', 'OS'), ('DBMS', 'DBMS'), ('AI', 'AI'))), ('5', (('DAA', 'DAA'), ('SAD', 'SAD'), ('CRYPTO', 'CRYPTO'), ('SAM', 'SAM'), ('WT', 'WT'), ('SAE', 'SAE'))), ('6', (('SE', 'SE'), ('CDC', 'CDC'), ('E-GOV', 'E-GOV'), ('NCC', 'NCC'), ('TW', 'TW'), ('E-COM', 'E-COM'))), ('7', (('AJP', 'AJP'), ('DW & DM', 'DW & DM'), ('POM', 'POM'), ('P-WORK', 'P-WORK'), ('IR', 'IR'), ('DA', 'DA'), ('SPM', 'SPM'), ('NS', 'NS'), ('DSD', 'DSD'))), ('8', (('AD', 'AD'), ('CC', 'CC'), ('AN-IPV6', 'AN-IPV6'), ('DSS & ES', 'DSS & ES'), ('DN', 'DN'), ('ESP', 'ESP'), ('GT', 'GT'), ('GS', 'GS'), ('IM', 'IM'), ('MAD', 'MAD'), ('NSA', 'NSA'), ('RTS', 'RTS')))], max_length=15)),
                ('MicroSyllabus_file', models.FileField(blank=True, default='NULL', null=True, upload_to='')),
                ('Book_file', models.FileField(blank=True, default='NULL', null=True, upload_to='')),
                ('Sub_discription', models.CharField(blank=True, max_length=100)),
                ('Sub_image', models.ImageField(blank=True, null=True, upload_to='subject_img')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.semester')),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
        migrations.AddField(
            model_name='question',
            name='Subject_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.semester'),
        ),
        migrations.AddField(
            model_name='note',
            name='Subject_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
        migrations.AddField(
            model_name='note',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.semester'),
        ),
    ]
