# Generated by Django 4.1.2 on 2023-04-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0009_note_question_semester_subject_delete_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth', 'Eighth')], max_length=15),
        ),
    ]
