# Generated by Django 4.1.2 on 2023-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0010_alter_semester_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Chapter',
            field=models.CharField(max_length=30),
        ),
    ]
